package cl.ips.pacs;

//from row number: 1
//PACS-CantidadCotizacionTramo-Hombre-1
rule "Row 1 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "1900-01-01" , fechaPension <= "2021-04-01" , sexo == "M" )
	then
		beneficiarioCC.setCantidadCotizaciones( 144 );
end

//from row number: 2
//PACS-CantidadCotizacionTramo-Hombre-2
rule "Row 2 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2021-04-02" , fechaPension <= "2022-04-01" , sexo == "M" )
	then
		beneficiarioCC.setCantidadCotizaciones( 150 );
end

//from row number: 3
//PACS-CantidadCotizacionTramo-Hombre-3
rule "Row 3 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2022-04-02" , fechaPension <= "2023-04-01" , sexo == "M" )
	then
		beneficiarioCC.setCantidadCotizaciones( 156 );
end

//from row number: 4
//PACS-CantidadCotizacionTramo-Hombre-4
rule "Row 4 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2023-04-02" , fechaPension <= "2024-04-01" , sexo == "M" )
	then
		beneficiarioCC.setCantidadCotizaciones( 162 );
end

//from row number: 5
//PACS-CantidadCotizacionTramo-Hombre-5
rule "Row 5 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2024-04-02" , fechaPension <= "2025-04-01" , sexo == "M" )
	then
		beneficiarioCC.setCantidadCotizaciones( 168 );
end

//from row number: 6
//PACS-CantidadCotizacionTramo-Hombre-6
rule "Row 6 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2025-04-01" , fechaPension <= "2026-04-01" , sexo == "M" )
	then
		beneficiarioCC.setCantidadCotizaciones( 174 );
end

//from row number: 7
//PACS-CantidadCotizacionTramo-Hombre-7
rule "Row 7 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2026-04-02" , fechaPension <= "9999-04-01" , sexo == "M" )
	then
		beneficiarioCC.setCantidadCotizaciones( 180 );
end

//from row number: 8
//PACS-CantidadCotizacionTramo-Mujer-1
rule "Row 8 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "1900-01-01" , fechaPension <= "2021-04-01" , sexo == "F" )
	then
		beneficiarioCC.setCantidadCotizaciones( 96 );
end

//from row number: 9
//PACS-CantidadCotizacionTramo-Mujer-2
rule "Row 9 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2021-04-02" , fechaPension <= "2022-04-01" , sexo == "F" )
	then
		beneficiarioCC.setCantidadCotizaciones( 102 );
end

//from row number: 10
//PACS-CantidadCotizacionTramo-Mujer-3
rule "Row 10 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2022-04-02" , fechaPension <= "2023-04-01" , sexo == "F" )
	then
		beneficiarioCC.setCantidadCotizaciones( 108 );
end

//from row number: 11
//PACS-CantidadCotizacionTramo-Mujer-4
rule "Row 11 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2023-04-02" , fechaPension <= "2024-04-01" , sexo == "F" )
	then
		beneficiarioCC.setCantidadCotizaciones( 114 );
end

//from row number: 12
//PACS-CantidadCotizacionTramo-Mujer-5
rule "Row 12 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2024-04-02" , fechaPension <= "2025-04-01" , sexo == "F" )
	then
		beneficiarioCC.setCantidadCotizaciones( 120 );
end

//from row number: 13
//PACS-CantidadCotizacionTramo-Mujer-6
rule "Row 13 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2025-04-02" , fechaPension <= "2026-04-01" , sexo == "F" )
	then
		beneficiarioCC.setCantidadCotizaciones( 120 );
end

//from row number: 14
//PACS-CantidadCotizacionTramo-Mujer-7
rule "Row 14 ReglasCantCotizaciones"
	no-loop true
	dialect "mvel"
	when
		beneficiarioCC : BeneficiarioCantidadCotizaciones( fechaPension >= "2026-04-02" , fechaPension <= "9999-04-01" , sexo == "F" )
	then
		beneficiarioCC.setCantidadCotizaciones( 120 );
end


