package cl.ips.pacs;

//from row number: 1
//Beneficiario fallecido
rule "Row 1 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion != "1900-01-01" )
	then
		beneficiario.setNumertotmp( 1 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Rechazo - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 2
//Es beneficiario PACS
rule "Row 2 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01" , beneficiarioPACS == 14 )
	then
		beneficiario.setNumertotmp( 14 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Rechazo - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 3
//Beneficiario no cumple edad
rule "Row 3 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01" , edad < 65 )
	then
		beneficiario.setNumertotmp( 2 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Rechazo - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 4
//Beneficiario  no cumple monto para el Variable
rule "Row 4 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01" , pensionUF >= 25.0 )
	then
		beneficiario.setNumertotmp( 4 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Rechazo - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 5
//Beneficiario  posee Inconsistencia por monto
rule "Row 5 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01" , montoInconsistencia == 10 , pensionUF < 25.0 )
	then
		beneficiario.setNumertotmp( 10 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Rechazo - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 6
//BRL_Beneficiario no cumple Cotizaciones PACS
rule "Row 6 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01" ,  poseeCotizacionesPACS == 1)
	then
		beneficiario.setNumertotmp( 8 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Rechazo - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 7
//BRL_Beneficiario posee Fecha Pension antes de Fecha Vigencia PACS
rule "Row 7 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01", poseeCotizacionesPACS != 1, fechaPension < ( beneficiario.fechaInicioVigenciaPACS ) )
	then
		beneficiario.setNumertotmp( 11 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Rechazo - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 8
//BRL_Beneficiario cumple Beneficio PACS Variable
rule "Row 8 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 14 , edad >= 65 , montoInconsistencia != 10 , pensionUF < 25.0 , poseeCotizacionesPACS != 1, fechaPension >= ( beneficiario.fechaInicioVigenciaPACS )  )
	then
		beneficiario.setNumertotmp( 9 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Aprueba - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end

//from row number: 9
//BRL_Beneficiario cumple Beneficio PACS Variable - Verifica Entidad Pagadora
rule "Row 9 ReglasElegibilidadVariable"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiario : BeneficiarioVectorVariable( fechaDefuncion == "1900-01-01" , edad >= 65 , montoInconsistencia != 10 , poseeCotizacionesPACS != 1, fechaPension >= ( beneficiario.fechaInicioVigenciaPACS ), vcEntidadPagadora == null  )
	then
		beneficiario.setNumertotmp( 22 );
		beneficiario.setTipoPACS( "Variable" );
		beneficiario.setEvaluacion( "Aprueba - PACS Variable" );
		beneficiario.addItem( beneficiario.numertotmp );
end