package cl.ips.pacs;

//from row number: 1
//Beneficiario esta fallecido
rule "Row 1 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion != "1900-01-01" )
	then
		beneficiarioF.setNumerotmp( 1 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 2
//Es beneficiario PACS
rule "Row 2 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01" , beneficiarioPACS == 12 )
	then
		beneficiarioF.setNumerotmp( 12 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 3
//Beneficiario no cumple edad
rule "Row 3 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01" , edad < 65 )
	then
		beneficiarioF.setNumerotmp( 2 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 4
//Beneficiario no cumple monto para el Fijo
rule "Row 4 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01" , pensionUF >= 25.0 )
	then
		beneficiarioF.setNumerotmp( 4 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 5
//Beneficiario posee Inconsistencia por monto
rule "Row 5 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01" , montoInconsistencia == 10 , pensionUF < 25.0 )
	then
		beneficiarioF.setNumerotmp( 10 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 6
//BRL_No cumple cotizaciones y con InconsistenciaIPS
rule "Row 6 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01",sumatoriaCotizaciones < ( beneficiarioF.cotizacionesExigidas ), (inconsistenciaIPS == 1 && bonoRecIPSAlternativa == 1) || (inconsistenciaIPS == 1 && bonoRecIPSAlternativa == 2) || (inconsistenciaIPS == 1 && bonoRecIPSAlternativa == 3))
	then
		beneficiarioF.setNumerotmp( 5 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 7
//BRL_verificaciones cotizaciones Dipreca
rule "Row 7 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo(fechaDefuncion == "1900-01-01",  sumatoriaCotizaciones < ( beneficiarioF.cotizacionesExigidas ),(inconsistenciaIPS == 1 && bonoRecIPSAlternativa != 1 && bonoRecIPSAlternativa != 2 && bonoRecIPSAlternativa != 3) || (inconsistenciaIPS == 0), bonoReconocimientoDIPRECA == 1, numeroCotzDipreca < 12 , sumatoriaCotizaciones + 48 >= ( beneficiarioF.cotizacionesExigidas ))
	then
		beneficiarioF.setNumerotmp( 20 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 8
//BRL_Verif Dipreca con cotiz menor a exigidas
rule "Row 8 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01" ,(inconsistenciaIPS == 1 && bonoRecIPSAlternativa != 1 && bonoRecIPSAlternativa != 2 && bonoRecIPSAlternativa != 3) || (inconsistenciaIPS == 0), numeroCotzDipreca >= 12, bonoReconocimientoDIPRECA == 1, sumatoriaCotizaciones < ( beneficiarioF.cotizacionesExigidas ) )
	then
		beneficiarioF.setNumerotmp( 6 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 9
//BRL_verificaciones cotizaciones Capredena
rule "Row 9 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01", (inconsistenciaIPS == 1 && bonoRecIPSAlternativa != 1 && bonoRecIPSAlternativa != 2 && bonoRecIPSAlternativa != 3) || (inconsistenciaIPS == 0), numeroCotzCapredena < 12  , bonoReconocimientoDIPRECA == 2, bonoReconocimientoCAPREDENA == 1, sumatoriaCotizaciones < ( beneficiarioF.cotizacionesExigidas ) , sumatoriaCotizaciones + 48 >= ( beneficiarioF.cotizacionesExigidas ))
	then
		beneficiarioF.setNumerotmp( 21 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 10
//BRL_Verif Capredena con cotiz menor a exigidas
rule "Row 10 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01", (inconsistenciaIPS == 1 && bonoRecIPSAlternativa != 1 && bonoRecIPSAlternativa != 2 && bonoRecIPSAlternativa != 3) || (inconsistenciaIPS == 0), numeroCotzCapredena >= 12, bonoReconocimientoDIPRECA == 2, bonoReconocimientoCAPREDENA == 1, sumatoriaCotizaciones < ( beneficiarioF.cotizacionesExigidas ))
	then
		beneficiarioF.setNumerotmp( 6 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 11
//BRL_Sin Dipreca Sin Capredena
rule "Row 11 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01",(inconsistenciaIPS == 1 && bonoRecIPSAlternativa != 1 && bonoRecIPSAlternativa != 2 && bonoRecIPSAlternativa != 3) || (inconsistenciaIPS == 0), sumatoriaCotizaciones < ( beneficiarioF.cotizacionesExigidas ) , bonoReconocimientoDIPRECA == 2, bonoReconocimientoCAPREDENA == 2)
	then
		beneficiarioF.setNumerotmp( 6 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Rechazo - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 12
//BRL_Beneficiario aplica beneficio
rule "Row 12 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , edad >= 65 , montoInconsistencia != 10 , pensionUF < 25.0, sumatoriaCotizaciones > ( beneficiarioF.cotizacionesExigidas ) )
	then
		beneficiarioF.setNumerotmp( 7 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Aprueba - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end

//from row number: 13
//BRL_Posee entidad pagadora
rule "Row 13 ReglasElegibilidadFijo"
	no-loop true
	enabled true
	dialect "mvel"
	when
		beneficiarioF : BeneficiarioVectorFijo( fechaDefuncion == "1900-01-01" , edad >= 65 , montoInconsistencia != 10, sumatoriaCotizaciones > ( beneficiarioF.cotizacionesExigidas ), vcEntidadPagadora == null )
	then
		beneficiarioF.setNumerotmp( 22 );
		beneficiarioF.setTipoPACS( "Fijo" );
		beneficiarioF.setEvaluacion( "Aprueba - PACS Fijo" );
		beneficiarioF.addItem( beneficiarioF.numerotmp );
end