package cl.ips.pacs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BeneficiarioCantidadCotizaciones implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Fecha Pension")
	private String fechaPension;
	@org.kie.api.definition.type.Label(value = "RUN")
	private java.lang.String run;
	@org.kie.api.definition.type.Label(value = "Sexo")
	private java.lang.String sexo;
	@org.kie.api.definition.type.Label(value = "Cantidad Cotizaciones")
	private int cantidadCotizaciones;

	public BeneficiarioCantidadCotizaciones() {
	}

	public String getFechaPension() {
		return this.fechaPension;
	}

	public void setFechaPension(String fechaPension) {
		this.fechaPension = fechaPension;
	}

	public java.lang.String getRun() {
		return this.run;
	}

	public void setRun(java.lang.String run) {
		this.run = run;
	}

	public java.lang.String getSexo() {
		return this.sexo;
	}

	public void setSexo(java.lang.String sexo) {
		this.sexo = sexo;
	}

	public int getCantidadCotizaciones() {
		return this.cantidadCotizaciones;
	}

	public void setCantidadCotizaciones(int cantidadCotizaciones) {
		this.cantidadCotizaciones = cantidadCotizaciones;
	}

	public BeneficiarioCantidadCotizaciones(String fechaPension,
			java.lang.String run, java.lang.String sexo,
			int cantidadCotizaciones) {
		this.fechaPension = fechaPension;
		this.run = run;
		this.sexo = sexo;
		this.cantidadCotizaciones = cantidadCotizaciones;
	}

	@Override
	public String toString() {
		return "BeneficiarioCantidadCotizaciones [fechaPension=" + fechaPension + ", run=" + run + ", sexo=" + sexo
				+ ", cantidadCotizaciones=" + cantidadCotizaciones + "]";
	}
	
}