package cl.ips.pacs;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BeneficiarioVectorVariable implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Beneficiario PACS")
	private int beneficiarioPACS;
	@org.kie.api.definition.type.Label("Edad")
	private int edad;
	@org.kie.api.definition.type.Label("Fecha Defuncion")
	private java.lang.String fechaDefuncion;
	@org.kie.api.definition.type.Label("Fecha Inicio Vigencia PACS")
	private java.lang.String fechaInicioVigenciaPACS;
	@org.kie.api.definition.type.Label("Fecha Pension")
	private java.lang.String fechaPension;
	@org.kie.api.definition.type.Label("Monto Inconsistencia")
	private int montoInconsistencia;
	@org.kie.api.definition.type.Label("Pension UF")
	private float pensionUF;
	@org.kie.api.definition.type.Label("Posee Cotizaciones PACS")
	private int poseeCotizacionesPACS;
	@org.kie.api.definition.type.Label("RUN")
	private java.lang.String run;
	@org.kie.api.definition.type.Label("Evaluacion Descripcion")
	private java.lang.String evaluacion;
	@org.kie.api.definition.type.Label("Numero Temporal")
	private java.lang.Integer numertotmp;
	@org.kie.api.definition.type.Label("Tipo PACS")
	private java.lang.String tipoPACS;
	@org.kie.api.definition.type.Label("Vector")
	private java.util.List<java.lang.Integer> vector = new ArrayList();

	@org.kie.api.definition.type.Label("Entidad Pagadora")
	private java.lang.String vcEntidadPagadora;

	public BeneficiarioVectorVariable() {
	}

	public void addItem(Integer valor) {
		if (!vector.contains(valor)) {
			vector.add(valor);
		}
	}

	public int getBeneficiarioPACS() {
		return this.beneficiarioPACS;
	}

	public void setBeneficiarioPACS(int beneficiarioPACS) {
		this.beneficiarioPACS = beneficiarioPACS;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public java.lang.String getFechaDefuncion() {
		return this.fechaDefuncion;
	}

	public void setFechaDefuncion(java.lang.String fechaDefuncion) {
		this.fechaDefuncion = fechaDefuncion;
	}

	public java.lang.String getFechaInicioVigenciaPACS() {
		return this.fechaInicioVigenciaPACS;
	}

	public void setFechaInicioVigenciaPACS(
			java.lang.String fechaInicioVigenciaPACS) {
		this.fechaInicioVigenciaPACS = fechaInicioVigenciaPACS;
	}

	public java.lang.String getFechaPension() {
		return this.fechaPension;
	}

	public void setFechaPension(java.lang.String fechaPension) {
		this.fechaPension = fechaPension;
	}

	public int getMontoInconsistencia() {
		return this.montoInconsistencia;
	}

	public void setMontoInconsistencia(int montoInconsistencia) {
		this.montoInconsistencia = montoInconsistencia;
	}

	public float getPensionUF() {
		return this.pensionUF;
	}

	public void setPensionUF(float pensionUF) {
		this.pensionUF = pensionUF;
	}

	public int getPoseeCotizacionesPACS() {
		return this.poseeCotizacionesPACS;
	}

	public void setPoseeCotizacionesPACS(int poseeCotizacionesPACS) {
		this.poseeCotizacionesPACS = poseeCotizacionesPACS;
	}

	public java.lang.String getRun() {
		return this.run;
	}

	public void setRun(java.lang.String run) {
		this.run = run;
	}

	public java.lang.String getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(java.lang.String evaluacion) {
		this.evaluacion = evaluacion;
	}

	public java.lang.Integer getNumertotmp() {
		return this.numertotmp;
	}

	public void setNumertotmp(java.lang.Integer numertotmp) {
		this.numertotmp = numertotmp;
	}

	public java.lang.String getTipoPACS() {
		return this.tipoPACS;
	}

	public void setTipoPACS(java.lang.String tipoPACS) {
		this.tipoPACS = tipoPACS;
	}

	public java.util.List<java.lang.Integer> getVector() {
		return this.vector;
	}

	public void setVector(java.util.List<java.lang.Integer> vector) {
		this.vector = vector;
	}

	public java.lang.String getVcEntidadPagadora() {
		return this.vcEntidadPagadora;
	}

	public void setVcEntidadPagadora(java.lang.String vcEntidadPagadora) {
		this.vcEntidadPagadora = vcEntidadPagadora;
	}

	public BeneficiarioVectorVariable(int beneficiarioPACS, int edad,
			java.lang.String fechaDefuncion,
			java.lang.String fechaInicioVigenciaPACS,
			java.lang.String fechaPension, int montoInconsistencia,
			float pensionUF, int poseeCotizacionesPACS, java.lang.String run,
			java.lang.String evaluacion, java.lang.Integer numertotmp,
			java.lang.String tipoPACS,
			java.util.List<java.lang.Integer> vector,
			java.lang.String vcEntidadPagadora) {
		this.beneficiarioPACS = beneficiarioPACS;
		this.edad = edad;
		this.fechaDefuncion = fechaDefuncion;
		this.fechaInicioVigenciaPACS = fechaInicioVigenciaPACS;
		this.fechaPension = fechaPension;
		this.montoInconsistencia = montoInconsistencia;
		this.pensionUF = pensionUF;
		this.poseeCotizacionesPACS = poseeCotizacionesPACS;
		this.run = run;
		this.evaluacion = evaluacion;
		this.numertotmp = numertotmp;
		this.tipoPACS = tipoPACS;
		this.vector = vector;
		this.vcEntidadPagadora = vcEntidadPagadora;
	}

	@Override
	public String toString() {
		return "BeneficiarioVectorVariable [beneficiarioPACS=" + beneficiarioPACS + ", edad=" + edad
				+ ", fechaDefuncion=" + fechaDefuncion + ", fechaInicioVigenciaPACS=" + fechaInicioVigenciaPACS
				+ ", fechaPension=" + fechaPension + ", montoInconsistencia=" + montoInconsistencia + ", pensionUF="
				+ pensionUF + ", poseeCotizacionesPACS=" + poseeCotizacionesPACS + ", run=" + run + ", evaluacion="
				+ evaluacion + ", numertotmp=" + numertotmp + ", tipoPACS=" + tipoPACS + ", vector=" + vector
				+ ", vcEntidadPagadora=" + vcEntidadPagadora + "]";
	}
	
	

}