package cl.ips.pacs;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BeneficiarioVectorFijo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Beneficiario PACS")
	private int beneficiarioPACS;
	@org.kie.api.definition.type.Label("Cotizaciones Exigidas")
	private int cotizacionesExigidas;
	@org.kie.api.definition.type.Label("Edad")
	private int edad;
	@org.kie.api.definition.type.Label("Fecha Defuncion")
	private java.lang.String fechaDefuncion;
	@org.kie.api.definition.type.Label("Inconsistencia IPS")
	private int inconsistenciaIPS;
	@org.kie.api.definition.type.Label("Monto Inconsistencia")
	private int montoInconsistencia;
	@org.kie.api.definition.type.Label("Pension UF")
	private float pensionUF;
	@org.kie.api.definition.type.Label("RUN")
	private java.lang.String run;
	@org.kie.api.definition.type.Label("Evaluacion Descripcion")
	private java.lang.String evaluacion;
	@org.kie.api.definition.type.Label("Numero Temporal")
	private java.lang.Integer numerotmp;
	@org.kie.api.definition.type.Label("Tipo PACS")
	private java.lang.String tipoPACS;
	@org.kie.api.definition.type.Label("Vector")
	private java.util.List<java.lang.Integer> vector = new ArrayList<java.lang.Integer>();

	@org.kie.api.definition.type.Label(value = "Bono Reconocimiento CAPREDENA")
	private int bonoReconocimientoCAPREDENA;

	@org.kie.api.definition.type.Label(value = "Bono Reconocimiento DIPRECA")
	private int bonoReconocimientoDIPRECA;

	@org.kie.api.definition.type.Label(value = "Sumatoria Cotizaciones")
	private int sumatoriaCotizaciones;

	@org.kie.api.definition.type.Label(value = "Entidad Pagadora")
	private java.lang.String vcEntidadPagadora;

	@org.kie.api.definition.type.Label(value = "Bono Reconocimiento IPS Alternativa")
	private int bonoRecIPSAlternativa;

	@org.kie.api.definition.type.Label(value = "Numero cotizaciones Dipreca")
	private int numeroCotzDipreca;

	@org.kie.api.definition.type.Label(value = "Numero cotizaciones Capredena")
	private int numeroCotzCapredena;

	public BeneficiarioVectorFijo() {
	}

	public void addItem(Integer valor) {
		if (!vector.contains(valor)) {
			vector.add(valor);
		}
	}

	public int getBeneficiarioPACS() {
		return this.beneficiarioPACS;
	}

	public void setBeneficiarioPACS(int beneficiarioPACS) {
		this.beneficiarioPACS = beneficiarioPACS;
	}

	public int getCotizacionesExigidas() {
		return this.cotizacionesExigidas;
	}

	public void setCotizacionesExigidas(int cotizacionesExigidas) {
		this.cotizacionesExigidas = cotizacionesExigidas;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public java.lang.String getFechaDefuncion() {
		return this.fechaDefuncion;
	}

	public void setFechaDefuncion(java.lang.String fechaDefuncion) {
		this.fechaDefuncion = fechaDefuncion;
	}

	public int getInconsistenciaIPS() {
		return this.inconsistenciaIPS;
	}

	public void setInconsistenciaIPS(int inconsistenciaIPS) {
		this.inconsistenciaIPS = inconsistenciaIPS;
	}

	public int getMontoInconsistencia() {
		return this.montoInconsistencia;
	}

	public void setMontoInconsistencia(int montoInconsistencia) {
		this.montoInconsistencia = montoInconsistencia;
	}

	public float getPensionUF() {
		return this.pensionUF;
	}

	public void setPensionUF(float pensionUF) {
		this.pensionUF = pensionUF;
	}

	public java.lang.String getRun() {
		return this.run;
	}

	public void setRun(java.lang.String run) {
		this.run = run;
	}

	public java.lang.String getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(java.lang.String evaluacion) {
		this.evaluacion = evaluacion;
	}

	public java.lang.Integer getNumerotmp() {
		return this.numerotmp;
	}

	public void setNumerotmp(java.lang.Integer numerotmp) {
		this.numerotmp = numerotmp;
	}

	public java.lang.String getTipoPACS() {
		return this.tipoPACS;
	}

	public void setTipoPACS(java.lang.String tipoPACS) {
		this.tipoPACS = tipoPACS;
	}

	public java.util.List<java.lang.Integer> getVector() {
		return this.vector;
	}

	public void setVector(java.util.List<java.lang.Integer> vector) {
		this.vector = vector;
	}

	public int getBonoReconocimientoCAPREDENA() {
		return this.bonoReconocimientoCAPREDENA;
	}

	public void setBonoReconocimientoCAPREDENA(int bonoReconocimientoCAPREDENA) {
		this.bonoReconocimientoCAPREDENA = bonoReconocimientoCAPREDENA;
	}

	public int getBonoReconocimientoDIPRECA() {
		return this.bonoReconocimientoDIPRECA;
	}

	public void setBonoReconocimientoDIPRECA(int bonoReconocimientoDIPRECA) {
		this.bonoReconocimientoDIPRECA = bonoReconocimientoDIPRECA;
	}

	public int getSumatoriaCotizaciones() {
		return this.sumatoriaCotizaciones;
	}

	public void setSumatoriaCotizaciones(int sumatoriaCotizaciones) {
		this.sumatoriaCotizaciones = sumatoriaCotizaciones;
	}

	public java.lang.String getVcEntidadPagadora() {
		return this.vcEntidadPagadora;
	}

	public void setVcEntidadPagadora(java.lang.String vcEntidadPagadora) {
		this.vcEntidadPagadora = vcEntidadPagadora;
	}

	public int getBonoRecIPSAlternativa() {
		return this.bonoRecIPSAlternativa;
	}

	public void setBonoRecIPSAlternativa(int bonoRecIPSAlternativa) {
		this.bonoRecIPSAlternativa = bonoRecIPSAlternativa;
	}

	public int getNumeroCotzDipreca() {
		return this.numeroCotzDipreca;
	}

	public void setNumeroCotzDipreca(int numeroCotzDipreca) {
		this.numeroCotzDipreca = numeroCotzDipreca;
	}

	public int getNumeroCotzCapredena() {
		return this.numeroCotzCapredena;
	}

	public void setNumeroCotzCapredena(int numeroCotzCapredena) {
		this.numeroCotzCapredena = numeroCotzCapredena;
	}

	public BeneficiarioVectorFijo(int beneficiarioPACS,
			int cotizacionesExigidas, int edad,
			java.lang.String fechaDefuncion, int inconsistenciaIPS,
			int montoInconsistencia, float pensionUF, java.lang.String run,
			java.lang.String evaluacion, java.lang.Integer numerotmp,
			java.lang.String tipoPACS,
			java.util.List<java.lang.Integer> vector,
			int bonoReconocimientoCAPREDENA, int bonoReconocimientoDIPRECA,
			int sumatoriaCotizaciones, java.lang.String vcEntidadPagadora,
			int bonoRecIPSAlternativa, int numeroCotzDipreca,
			int numeroCotzCapredena) {
		this.beneficiarioPACS = beneficiarioPACS;
		this.cotizacionesExigidas = cotizacionesExigidas;
		this.edad = edad;
		this.fechaDefuncion = fechaDefuncion;
		this.inconsistenciaIPS = inconsistenciaIPS;
		this.montoInconsistencia = montoInconsistencia;
		this.pensionUF = pensionUF;
		this.run = run;
		this.evaluacion = evaluacion;
		this.numerotmp = numerotmp;
		this.tipoPACS = tipoPACS;
		this.vector = vector;
		this.bonoReconocimientoCAPREDENA = bonoReconocimientoCAPREDENA;
		this.bonoReconocimientoDIPRECA = bonoReconocimientoDIPRECA;
		this.sumatoriaCotizaciones = sumatoriaCotizaciones;
		this.vcEntidadPagadora = vcEntidadPagadora;
		this.bonoRecIPSAlternativa = bonoRecIPSAlternativa;
		this.numeroCotzDipreca = numeroCotzDipreca;
		this.numeroCotzCapredena = numeroCotzCapredena;
	}

	@Override
	public String toString() {
		return "BeneficiarioVectorFijo [beneficiarioPACS=" + beneficiarioPACS + ", cotizacionesExigidas="
				+ cotizacionesExigidas + ", edad=" + edad + ", fechaDefuncion=" + fechaDefuncion
				+ ", inconsistenciaIPS=" + inconsistenciaIPS + ", montoInconsistencia=" + montoInconsistencia
				+ ", pensionUF=" + pensionUF + ", run=" + run + ", evaluacion=" + evaluacion + ", numerotmp="
				+ numerotmp + ", tipoPACS=" + tipoPACS + ", vector=" + vector + ", bonoReconocimientoCAPREDENA="
				+ bonoReconocimientoCAPREDENA + ", bonoReconocimientoDIPRECA=" + bonoReconocimientoDIPRECA
				+ ", sumatoriaCotizaciones=" + sumatoriaCotizaciones + ", vcEntidadPagadora=" + vcEntidadPagadora
				+ ", bonoRecIPSAlternativa=" + bonoRecIPSAlternativa + ", numeroCotzDipreca=" + numeroCotzDipreca
				+ ", numeroCotzCapredena=" + numeroCotzCapredena + "]";
	}

	
	
}