package cl.ips.pacs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BeneficiarioCodTipoElegibilidad implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "RUN")
	private java.lang.String run;
	private java.util.List<java.lang.Integer> vectorPACSFijo;
	private java.util.List<java.lang.Integer> vectorPACSVariable;
	@org.kie.api.definition.type.Label(value = "CodigoTipoElegibilidad")
	private int codigoTipoElegibilidad;

	public BeneficiarioCodTipoElegibilidad() {
	}

	public java.lang.String getRun() {
		return this.run;
	}

	public void setRun(java.lang.String run) {
		this.run = run;
	}

	public java.util.List<java.lang.Integer> getVectorPACSFijo() {
		return this.vectorPACSFijo;
	}

	public void setVectorPACSFijo(
			java.util.List<java.lang.Integer> vectorPACSFijo) {
		this.vectorPACSFijo = vectorPACSFijo;
	}

	public java.util.List<java.lang.Integer> getVectorPACSVariable() {
		return this.vectorPACSVariable;
	}

	public void setVectorPACSVariable(
			java.util.List<java.lang.Integer> vectorPACSVariable) {
		this.vectorPACSVariable = vectorPACSVariable;
	}

	public int getCodigoTipoElegibilidad() {
		return this.codigoTipoElegibilidad;
	}

	public void setCodigoTipoElegibilidad(int codigoTipoElegibilidad) {
		this.codigoTipoElegibilidad = codigoTipoElegibilidad;
	}

	public BeneficiarioCodTipoElegibilidad(java.lang.String run,
			java.util.List<java.lang.Integer> vectorPACSFijo,
			java.util.List<java.lang.Integer> vectorPACSVariable,
			int codigoTipoElegibilidad) {
		this.run = run;
		this.vectorPACSFijo = vectorPACSFijo;
		this.vectorPACSVariable = vectorPACSVariable;
		this.codigoTipoElegibilidad = codigoTipoElegibilidad;
	}

	@Override
	public String toString() {
		return "BeneficiarioCodTipoElegibilidad [run=" + run + ", vectorPACSFijo=" + vectorPACSFijo
				+ ", vectorPACSVariable=" + vectorPACSVariable + ", codigoTipoElegibilidad=" + codigoTipoElegibilidad
				+ "]";
	}
	
	
	

}