package cl.ips.pacs;


import cl.gob.ips.poc.test_drl_poc_ips.DatosBeneficiarioPacsFijoVector
import cl.gob.ips.poc.test_drl_poc_ips.RespuestaPACSVectorNuevo


//from row number: 1
//Beneficiario esta fallecido
rule "Row 1 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion != "1900-01-01" )
	then
		beneficiario.setPensionUF( 12.4 );
end

//from row number: 2
//Es beneficiario PACS
rule "Row 2 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS == 12 )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 12 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Rechazo - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 3
//Beneficiario no cumple edad
rule "Row 3 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , edad < 65 )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 2 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Rechazo - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 4
//Beneficiario no es pensionado
rule "Row 4 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , pensionado != 0 )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 3 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Rechazo - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 5
//Beneficiario posee Inconsistencia por monto
rule "Row 5 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , pensionado == 0 , montoInconsistencia == 10 )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 10 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Rechazo - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 6
//Beneficiario no cumple monto para el Fijo
rule "Row 6 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , pensionado == 0 , montoInconsistencia != 10 , pensionUF >= 25.0 )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 4 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Rechazo - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 7
//Beneficiario no cumple cotizaciones AFPDiCa y con Inconsistencia Bono IPS
rule "Row 7 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , pensionado == 0 , inconsistenciaIPS == 1 )
		DatosBeneficiarioPacsFijoVector( cotizacionesPoseeAFPDiCa < ( beneficiario.cotizacionesExigidas ) )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 5 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Rechazo - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 8
//Beneficiario no cumple cotizaciones AFPDiCa y No cumple cotizaciones
rule "Row 8 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , pensionado == 0 , inconsistenciaIPS == 0 )
		DatosBeneficiarioPacsFijoVector( cotizacionesPoseeAFPDiCa < ( beneficiario.cotizacionesExigidas ) )
		DatosBeneficiarioPacsFijoVector( cotizacionesPoseeTotal < ( beneficiario.cotizacionesExigidas ) )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 6 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Rechazo - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 9
//Beneficiario aplica beneficio con Cotizaciones AFPDiCa mayor a Cotizaciones Exigidas
rule "Row 9 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" , beneficiarioPACS != 12 , edad >= 65 , pensionado == 0 , montoInconsistencia != 10 , pensionUF < 25.0 )
		DatosBeneficiarioPacsFijoVector( cotizacionesPoseeAFPDiCa >= ( beneficiario.cotizacionesExigidas ) )
		respuesta : RespuestaPACSVectorNuevo( activar == true , run == ( beneficiario.run ) )
	then
		respuesta.setNumerotmp( 7 );
		respuesta.setTipoPACS( "Fijo" );
		respuesta.setEvaluacion( "Aprueba - PACS Fijo" );
		respuesta.addItem( respuesta.numerotmp, beneficiario.run );
		System.out.println("Run: " + respuesta.getRun() + ",  vector: " + respuesta.getVector() );
end

//from row number: 10
//Beneficiario aplica beneficio con Cotizaciones Posee mayor a Cotizaciones Exigidas
rule "Row 10 ReglasPACSFijoGuided"
	no-loop true
	dialect "mvel"
	when
		beneficiario : DatosBeneficiarioPacsFijoVector( fechaDefuncion == "1900-01-01" )
	then
		beneficiario.setPensionUF( 22.4 );
end

